emacs: package-reinstall magit (fixes editor error on commit)
Fixes the following error when attempting to commit with magit, after
upgrading from emacs 27.2 -> 29.1:

  0 git … add -u .
  1 git … commit --
hint: Waiting for your editor to close the file... Waiting for Emacs...
*ERROR*: Wrong number of arguments: ((t) (fn &optional next-buffer killed-one filepos) "Honor `with-editor-server-window-alist' (which see)." (let ((server-window (save-current-buffer (set-buffer (or next-buffer (current-buffer))) (if with-editor-mode (progn (setq with-editor-previous-winconf (current-window-configuration)))) (with-editor-server-window)))) (funcall fn next-buffer killed-one filepos))), 5
error: There was a problem with the editor '/home/benv/stow/emacs-29.1/bin/emacsclient --socket-name=/tmp/emacs1000/server'.
Please supply the message using either -m or -F option.